apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ajay/Desktop/data
