apiVersion: v1
kind: Pod
metadata:
    name: myfirstpod
    labels: 
       env: prod
spec:
  containers:
    - name : firstcontainer
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
    - name : secondc
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
  initContainers:
    - name : initcontainer
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
      args: ["sleep" ,"10"]
    - name : initcontainer1
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
      args: ["sleep" ,"10"]

