apiVersion: v1
kind: Pod
metadata:
    name: fourthpod
    labels: 
       env: prod
spec:
  containers:
    - name : containername
      image : nginx
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
    #  args: ["sleep","50" ]

