apiVersion: v1
kind: Pod
metadata:
    name: myfirstpod
    labels: 
       env: prod
spec:
  containers:
    - name : containername
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
      args: ["sleep","50" ]
    - name : containername2
      image : coolgourav147/nginx-custom
      env:
        - name: myname
          value: ajay
        - name: city
          value: abad
