kind: ReplicationController
apiVersion: v1
metadata:
  name: firstrc
  labels:
    appname: votingapp

spec:
  replicas: 1
  template:
    metadata:
      name: secondpod
      labels: 
        type: app
    spec:
      containers:
        - image: nginx
          name: c1
